include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

.gpu:
  extends: .test
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.add("CuArrays");
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.test(; coverage=true);'


julia:1.0:
  extends:
    - .julia:1.0
    - .gpu
  tags:
    - nvidia

julia:1.1:
  extends:
    - .julia:1.1
    - .gpu
  tags:
    - nvidia

julia:1.2:
  extends:
    - .julia:1.2
    - .gpu
  tags:
    - nvidia

julia:1.3:
  extends:
    - .julia:1.3
    - .gpu
  tags:
    - nvidia
  allow_failure: true

julia:nightly:
  extends:
    - .julia:nightly
    - .gpu
  tags:
    - nvidia
  allow_failure: true

coverage:
    extends:
    - .julia:1.2
    - .coverage
