language: julia
os:
  - linux
  # - osx

julia:
  - 1.0
  - 1.1
  - nightly

branch:
  only:
    - master

after_success:
  - if [[ $TRAVIS_JULIA_VERSION = 1.1 ]] && [[ $TRAVIS_OS_NAME = linux ]]; then
      julia -e 'cd(Pkg.dir("MyPkg")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
      # julia --project=test/coverage -e 'using Pkg; Pkg.instantiate();
      #     using Coverage; Codecov.submit(Codecov.process_folder())';
    fi

notifications:
  email: false

git:
  depth: 99999999
